"""
Highly divisible triangular number
Euler Project - Problem 12 
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
"""
import time

start_time = time.time()


def tri_numbers(n):
    sum = 1
    trilist = [1]
    for i in range(2, n):
        sum = i + trilist[-1]
        trilist.append(sum)
    return trilist


def factors(n):
    return list(set(
        factor for i in range(1, int(n**0.5) + 1) if n % i == 0
        for factor in (i, n // i)))


# print(factors(10))
#print (tri_numbers(100))

# main
#item = (input("Enter number: "))
item = 1
for item in tri_numbers(20000):
    if len(factors(item)) > 500:
        #print(item, factors(item), len(factors(item)))
        print(item, len(factors(item)))
        break
    item = item + 1
print("--- %s seconds ---" % (time.time() - start_time))
